trans: seção 7, subseções 1 e 2
HenriqueAJNB/data-science-escalavel pull request #41
Opened 2022-05-10 01:00 UTC by arturovaine

Início da tradução da seção 7, subseções 1 e 2.

2022-05-10 15:19 UTC, HenriqueAJNB requested changes

2022-05-10 15:19 UTC, HenriqueAJNB commented on book/cap07-introducao_ao_DVC/sec7-1-introducao_ao_DVC_Controle_de_versionamento_de_dados.md
> +Encontre as instruções sobre mais formas de instalar o DVC <a href='https://dvc.org/doc/install'>aqui</a>.
Sugiro alterar para a sintaxe de links do Markdown para mantermos o padrão, ao invés de usar a tag `a` com atributo `href` do HTML =)

O efeito para o leitor final é indiferente, mas é legal para mantermos um padrão do desenvolvimento anterior.

2022-05-10 15:20 UTC, HenriqueAJNB commented
FIcou muito bom @arturovaine. Só sugiro alterar as formatações todas para Markdown e acrescentar a linguagem quando você coloca qualquer tipo de comando/código. Feito tais modificações, aprovo seu PR!

2022-05-10 19:32 UTC, arturovaine commented
> FIcou muito bom @arturovaine. Só sugiro alterar as formatações todas para Markdown e acrescentar a linguagem quando você coloca qualquer tipo de comando/código. Feito tais modificações, aprovo seu PR!

Tudo certo @HenriqueAJNB , tinha deixado passar padronização. Acho que cobri o que faltava, senão é só avisar.

2022-05-11 00:21 UTC, HenriqueAJNB commented
A única coisa que mantenho de HTML é a `div` para justificar o texto, porque não existe essa formatação em markdown...

2022-05-11 00:21 UTC, HenriqueAJNB approved these changes

2022-05-11 00:22 UTC, merged

2022-05-11 00:22 UTC, HenriqueAJNB commented
@all-contributors please add @arturovaine as content